/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting;

import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Luqmaan
 */
public class Instructions_BackUP extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Instructions_BackUP() {
        initComponents();

        jTextArea1.setOpaque(false);
        //jTextArea1.setBackground(null);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretPosition(0);

        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setBackground(new Color(0, 0, 0, 0));
        //jScrollPane2.getVerticalScrollBar().setOpaque(false);
        jScrollPane2.setBorder(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INSTRUCTIONS MANUAL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 190, 400, 40);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GO TO LOGIN");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 630, 160, 40);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(65, 65, 65));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("                                                              Welcome to a Product of Furqaan Developments\n\n                                                     Read the following guidelines before using the Application\n\n 1) If you wish to access the Secret Functions of the Applications, you might as well need a \"Secret Code\", which                        corresponds to the SYMBOLS UPON THE DATE OF BIRTH OF THE DEVELOPER.                                                                              (DDMMYY ; Year being - 00 for 2000, 01 for 2001, so on)\n    Or which can also found in the instructions File provided.\n\n 2) On prompted to choose the DEFAULT DIRECTORY, Make sure to Select the Folder which Contains the Pictures of all the\t    Candidates in 'JPEG' FORMAT. \n\n 3) It is significant to be particular about the NAMING AND DIMENSIONS of the pictures of candidates.\n    Two methods for Voting have been designed each with its own resources.\n\n     i) INDIVIDUAL VOTING -\n       Naming - Name of the candidates to be the same as the name registered in the 'ADD/REMOVE CANDIDATES' Menu\n       Dimensions - 250x250 pixels\n\n    ii) MULTIPLE VOTING - \n       Naming - Name of the candidates to be the same as the name registered in the 'ADD/REMOVE CANDIDATES' Menu                 with a 'S' before the name   (e.g. Name of the Candidate - RAKESH  ; Name of the Picture to be - 'SRAKESH')\n       Dimensions - 100x100 pixels \n\n 4) It is most IMPORTANT that you have read and understood all the guidelines.\n\n 5) Stay Tuned and HAPPY VOTING :)\n\n 6) For Details or queries \n          Send a mail to  -       furqaanhashim@gmail.com\n          or Contact         -       +919480017396\n     ");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 240, 1100, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/res/EVoting VSmall.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 0, 190, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1216, 714));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String comments = "create table location(Location varchar(200));";

            stmt.executeUpdate(comments);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String admins = "create table admins(name varchar(100), password varchar(100));";

            stmt.executeUpdate(admins);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String login_info = "create table login_info(name varchar(100), time varchar(20), access varchar(20));";

            stmt.executeUpdate(login_info);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String headboy = "create table headboy(name varchar(50), count int(6));";

            stmt.executeUpdate(headboy);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String headgirl = "create table headgirl(name varchar(50), count int(6));";

            stmt.executeUpdate(headgirl);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }
        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String cultural = "create table cultural(name varchar(50), count int(6));";

            stmt.executeUpdate(cultural);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String sports = "create table sports(name varchar(50), count int(6));";

            stmt.executeUpdate(sports);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String query = "select *from Location";

            ResultSet rs = stmt.executeQuery(query);

            if (rs.next() != true) {
                JOptionPane.showMessageDialog(null, "Default Path does not exist \nPlease add the Path now");

                JFileChooser browse = new JFileChooser();
                browse.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                int a = browse.showDialog(null, "Save Directory");
                if (a == JFileChooser.APPROVE_OPTION) {
                    File file = browse.getSelectedFile();

                    String path = file.getAbsoluteFile().toString().replace("\\", "/");
                    query = "insert into Location values('" + path + "');";
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Directory Added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Add the Directory later from Tools Menu");
                }

            }

            con.close();
            rs.close();
            stmt.close();

        } catch (Exception e) {

        }
        Login login = new Login();
        login.setVisible(true);

        JOptionPane.showMessageDialog(login, "Archive has been Created");
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructions_BackUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructions_BackUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructions_BackUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructions_BackUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructions_BackUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
